export { default as Article} from './Articles/Article'
export { default as Brand} from './Brand/Brand'
export { default as CTA} from './CTA/CTA'
export { default as Feature} from './Features/Feature'
export { default as NavBar} from './NavBar/NavBar'